##########################################################
#                  GOLANG SERVICES                       #
##########################################################

  db:
    image: dubrovin/epam-db
    ports:
      - 8080:8080

#  watcher:
#    image: dubrovin/epam-watcher
#    ports:
#      - 8081:8081
#
#  reserver:
#    image: dubrovin/epam-reserver
#    ports:
#      - 8082:8082